In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('india_evcharging.csv')

In [3]:
df.shape

(171, 11)

In [4]:
df.sample(5)

,Unnamed: 0,name,connectors,formatted_address,address_components,latitude,longitude,place_link,phone_number,rating,review_count
40,40,BPCL Charging Station,"[{'type': 'CCS', 'total': 2, 'available': 1, '...","JWMG+MWC, RO AT DAHEGAON, Mahar, Nagpur, Wardh...","{'district': 'Mahar', 'street_address': 'JWMG+...",20.634187,78.927256,https://www.google.com/maps/place/data=!3m1!4b...,NaN,3.7,3
93,93,Ankush Vehicles,[],Chhattisgarh 495690,"{'district': None, 'street_address': None, 'ci...",21.848500,82.779109,https://www.google.com/maps/place/data=!3m1!4b...,NaN,5.0,1
160,160,Tata EV charging station,[],"1/469/24, VGP MANGALPURI TOWN POOMALUR, Tirupp...","{'district': 'VGP MANGALPURI TOWN POOMALUR', '...",21.032392,79.051893,https://www.google.com/maps/place/data=!3m1!4b...,NaN,5.0,1
137,137,Ather Grid Charging Station,"[{'type': 'LECCS', 'total': 1, 'available': 1,...","Dhabha Toll Tax, near, Katol Bypass Rd, Wadi, ...","{'district': 'Wadi', 'street_address': 'Dhabha...",21.157442,79.008200,https://www.google.com/maps/place/data=!3m1!4b...,NaN,1.0,1
124,124,Adani Charging Station,"[{'type': 'Type 2', 'total': 2, 'available': 0...","No. 59/1, Forest Gatesv, Mohurli, 60/1, near M...","{'district': 'MIDC', 'street_address': 'No. 59...",20.191296,79.334224,https://www.google.com/maps/place/data=!3m1!4b...,NaN,NaN,0

In [5]:
df.isnull().count()

Unnamed: 0            171
name                  171
connectors            171
formatted_address     171
address_components    171
latitude              171
longitude             171
place_link            171
phone_number          171
rating                171
review_count          171
dtype: int64

In [6]:
df.describe()

,Unnamed: 0,latitude,longitude,phone_number,rating,review_count
count,171.000000,171.000000,171.000000,2.000000e+00,104.000000,171.000000
mean,85.000000,21.136435,80.649060,1.888334e+10,3.636538,2.701754
std,49.507575,0.329499,1.571167,0.000000e+00,1.290372,6.703726
min,0.000000,20.088792,78.476983,1.888334e+10,1.000000,0.000000
25%,42.500000,21.042628,79.044471,1.888334e+10,3.000000,0.000000
50%,85.000000,21.147218,81.585515,1.888334e+10,3.750000,1.000000
75%,127.500000,21.243997,81.691613,1.888334e+10,5.000000,3.000000
max,170.000000,22.046612,83.944182,1.888334e+10,5.000000,76.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          171 non-null    int64
 1   name                171 non-null    object
 2   connectors          171 non-null    object
 3   formatted_address   171 non-null    object
 4   address_components  171 non-null    object
 5   latitude            171 non-null    float64
 6   longitude           171 non-null    float64
 7   place_link          171 non-null    object
 8   phone_number        2 non-null      float64
 9   rating              104 non-null    float64
 10  review_count        171 non-null    int64
dtypes: float64(4), int64(2), object(5)
memory usage: 14.8+ KB

ValueError: could not convert string to float: 'Adani Charging Station'