Ordinal Encoding

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np

In [8]:
df=pd.read_csv('glue.csv')

In [9]:
df.sample(5)

          Model  Year      Encoder   Task  Score
24        ERNIE  2019  Transformer  STS-B   93.0
49           T5  2019  Transformer   QNLI   96.9
62  BiLSTM+Attn  2017         LSTM    RTE   58.4
43         BERT  2018  Transformer   MNLI   86.7
0         ERNIE  2019  Transformer   CoLA   75.5

In [10]:
df.shape

(64, 5)

In [15]:
df['Encoder'].value_counts()

Encoder
Transformer    32
LSTM           32
Name: count, dtype: int64

In [ ]:
df['Year'].value_counts()
#ordinal encoding

Year
2019    24
2017    24
2018    16
Name: count, dtype: int64

In [ ]:
df['Model'].value_counts()
# one hot encoding

Model
ERNIE          8
T5             8
RoBERTa        8
BERT           8
BiLSTM+ELMo    8
BiLSTM+CoVe    8
BiLSTM+Attn    8
BiLSTM         8
Name: count, dtype: int64

In [ ]:
df['Task'].value_counts()
#one hot encdoing

Task
CoLA     8
SST-2    8
MRPC     8
STS-B    8
QQP      8
MNLI     8
QNLI     8
RTE      8
Name: count, dtype: int64

In [44]:
df2 = df[['Year']]   # DataFrame (2D)

In [45]:

df2

    Year
0   2019
1   2019
2   2019
3   2018
4   2018
..   ...
59  2018
60  2018
61  2017
62  2017
63  2017

[64 rows x 1 columns]

In [46]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[[2017, 2018, 2019]])

oe.fit(df2)
newdata = oe.transform(df2)

In [49]:
print(newdata)

[[2.]
 [2.]
 [2.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [2.]
 [2.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [2.]
 [2.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [2.]
 [2.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [2.]
 [2.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [2.]
 [2.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [2.]
 [2.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [2.]
 [2.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]]

In [51]:
type(newdata)

numpy.ndarray

In [52]:
df_new = pd.DataFrame(newdata)

In [53]:
df_new

      0
0   2.0
1   2.0
2   2.0
3   1.0
4   1.0
..  ...
59  1.0
60  1.0
61  0.0
62  0.0
63  0.0

[64 rows x 1 columns]

In [54]:
df

          Model  Year      Encoder  Task  Score
0         ERNIE  2019  Transformer  CoLA   75.5
1            T5  2019  Transformer  CoLA   71.6
2       RoBERTa  2019  Transformer  CoLA   67.8
3          BERT  2018  Transformer  CoLA   60.5
4   BiLSTM+ELMo  2018         LSTM  CoLA   32.1
..          ...   ...          ...   ...    ...
59         BERT  2018  Transformer   RTE   70.1
60  BiLSTM+ELMo  2018         LSTM   RTE   57.4
61  BiLSTM+CoVe  2017         LSTM   RTE   52.7
62  BiLSTM+Attn  2017         LSTM   RTE   58.4
63       BiLSTM  2017         LSTM   RTE   57.4

[64 rows x 5 columns]

In [55]:
from sklearn.preprocessing import LabelEncoder

In [56]:
df3=df[['Encoder']]

In [58]:
df3.value_counts()

Encoder
LSTM           32
Transformer    32
Name: count, dtype: int64

In [59]:
le=LabelEncoder()

In [60]:
le.fit(df3)

c:\Users\rayph\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LabelEncoder()

In [61]:
le.classes_

array(['LSTM', 'Transformer'], dtype=object)

In [63]:
df3_new=le.transform(df3)

c:\Users\rayph\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [65]:
df3_new

array([1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0])

In [67]:
df3

        Encoder
0   Transformer
1   Transformer
2   Transformer
3   Transformer
4          LSTM
..          ...
59  Transformer
60         LSTM
61         LSTM
62         LSTM
63         LSTM

[64 rows x 1 columns]

one hot encoding

In [76]:
data=pd.read_csv('cars.csv')

In [77]:
data.sample(4)

          brand  km_driven    fuel         owner  selling_price
8080       Tata     100000  Diesel   First Owner         300000
6279     Toyota      91000  Diesel  Second Owner        1650000
7928     Maruti      30154  Diesel   First Owner         630000
3791  Chevrolet      56315  Diesel   First Owner         175000

In [71]:
data['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [72]:
data['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [89]:
x_train_new=pd.get_dummies(data,columns=['fuel'],drop_first=True,dtype=int)

In [ ]:
x_train_new

,brand,km_driven,owner,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,First Owner,450000,1,0,0
1,Skoda,120000,Second Owner,370000,1,0,0
2,Honda,140000,Third Owner,158000,0,0,1
3,Hyundai,127000,First Owner,225000,1,0,0
4,Maruti,120000,First Owner,130000,0,0,1
...,...,...,...,...,...,...,...
8123,Hyundai,110000,First Owner,320000,0,0,1
8124,Hyundai,119000,Fourth & Above Owner,135000,1,0,0
8125,Maruti,120000,First Owner,382000,1,0,0
8126,Tata,25000,First Owner,290000,1,0,0
8127,Tata,25000,First Owner,290000,1,0,0

In [84]:
counts=data['brand'].value_counts()

In [85]:
counts.head(2)

brand
Maruti     2448
Hyundai    1415
Name: count, dtype: int64

In [86]:
threshold=100
repl=counts[counts<=threshold].index

In [93]:
x_train_new2=pd.get_dummies(x_train_new['brand'].replace(repl,'others'),drop_first=True,dtype=int)

In [99]:
x_train_new2.sample(5)

,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,others
1941,0,0,0,0,0,0,0,0,0,0,0,1
593,0,0,0,0,0,0,1,0,0,0,0,0
7945,0,0,0,0,0,0,0,0,0,1,0,0
6031,0,1,0,0,0,0,0,0,0,0,0,0
4246,0,0,0,0,0,1,0,0,0,0,0,0

In [102]:
fulltraindata=pd.concat([x_train_new,x_train_new2],axis=1)

In [103]:
fulltraindata.sample(5)

,brand,km_driven,owner,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,others
3193,Renault,50000,First Owner,900000,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
1712,Tata,110000,First Owner,503000,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3906,Hyundai,49000,First Owner,1150000,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0
8103,Maruti,100000,Second Owner,130000,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
2382,Maruti,130376,Second Owner,265000,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0

In [106]:
fulltraindata=fulltraindata.drop('brand',axis=1)

In [108]:
fulltraindata.sample(5)

,km_driven,owner,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,others
1170,40000,First Owner,340000,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
5983,65000,Second Owner,695000,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
7314,70000,Third Owner,150000,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0
3044,76000,Second Owner,380000,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
7762,36800,First Owner,695000,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [110]:
fulltraindata.shape

(8128, 18)

In [113]:
fulltraindata['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [111]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe=OrdinalEncoder(categories=[['Fourth & Above Owner','Third Owner','Second Owner','First Owner','Test Drive Car']])

In [116]:
fulltraindata['owner']=oe.fit_transform(fulltraindata[['owner']])

In [120]:
fulltraindata.sample(5)

,km_driven,owner,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,others
833,20000,3.0,235000,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
3367,38000,3.0,540000,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0
2057,80000,3.0,150000,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0
3443,35000,3.0,400000,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
6881,40000,2.0,1630000,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [121]:
fulltraindata['owner'].value_counts()

owner
3.0    5289
2.0    2105
1.0     555
0.0     174
4.0       5
Name: count, dtype: int64

First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5