In [70]:
from sklearn.datasets import load_diabetes
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
import pandas as pd

In [71]:
df=pd.read_csv('adult.csv')

In [72]:
df.sample(5)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
9247,23,Private,305423,Bachelors,13,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,<=50K
36489,33,Self-emp-inc,144949,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,65,United-States,<=50K
45775,39,State-gov,142897,Assoc-voc,11,Never-married,Exec-managerial,Unmarried,White,Female,0,0,50,United-States,<=50K
22067,43,Private,361280,10th,6,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,42,China,<=50K
45256,38,Self-emp-not-inc,172342,Some-college,10,Divorced,Other-service,Unmarried,White,Female,0,0,40,United-States,<=50K

In [73]:
drop_coulumns=['fnlwgt','education']

In [74]:
df=df.drop(columns=drop_coulumns)

In [75]:
df

,age,workclass,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [76]:
df.sample()

,age,workclass,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
42486,18,State-gov,9,Never-married,Adm-clerical,Own-child,Black,Male,0,0,15,United-States,<=50K

In [77]:
df.value_counts(['workclass'])

workclass
Private             33906
Self-emp-not-inc     3862
Local-gov            3136
?                    2799
State-gov            1981
Self-emp-inc         1695
Federal-gov          1432
Without-pay            21
Never-worked           10
Name: count, dtype: int64

In [78]:
df = df[df['workclass'] != '?']

In [79]:
df.value_counts(['workclass'])

workclass
Private             33906
Self-emp-not-inc     3862
Local-gov            3136
State-gov            1981
Self-emp-inc         1695
Federal-gov          1432
Without-pay            21
Never-worked           10
Name: count, dtype: int64

In [80]:
df['workclass']=pd.get_dummies(df['workclass'],drop_first=True)

ValueError: Columns must be same length as key

In [ ]:
x=df.iloc[:,:12]
y=df.iloc[:,12:13]

In [ ]:
y.sample(5)

      income
356    <=50K
1024   <=50K
29967  <=50K
4055   <=50K
12463   >50K

In [ ]:

x_train,x_test,y_train,y_test=train_test_split(
    x,y,random_state=42,test_size=0.25
)

In [ ]:
regressor=DecisionTreeRegressor(max_depth=None)
regressor.fit(x_train,y_train)

ValueError: could not convert string to float: '?'